version: '2'
services:
#---WEBSIG-------------------------------------
  lizmap:
    image: jancelin/geopoppy:qgis2.14-lizmap3.1
    restart: always
    ports:
     - "80:80"
     - "443:443"
    volumes:
     - "/home/GeoPoppy/lizmap/project:/home"
     - "/home/GeoPoppy/lizmap/project/var:/var/www/websig/lizmap/var"
     - "/home/GeoPoppy/lizmap/project/tmp:/tmp"
#---Bases de données----------------------------------
  postgis:
    image: jancelin/geopoppy:postgis
    restart: always
    ports:
     - "5432:5432"
    volumes:
     - "/home/GeoPoppy/postgres_data:/var/lib/postgresql"
#---Outils--------------------------------------------   
  portainer:
    image: portainer/portainer:linux-arm
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      
  pgadmin4:
    image: jancelin/geopoppy:pgadmin4-beta1
    ports:
     - "5050:5050"
    volumes:
    #--ne pas oublier de créer le dossier:  mkdir /home/GeoPoppy/pgadmin4/pgadmin_data
     - "/home/GeoPoppy/pgadmin4/pgadmin_data:/pgadmin"
