# Rename to docker-compose.yml
# play with HYPRIOT-OS-32bits : https://blog.hypriot.com/downloads/
# Flash microSD with etcher: https://etcher.io/
# MAINTAINER Julien Ancelin <julien.ancelin@inra.fr>
version: '3.2'
services:
  lizmap:
    image: jancelin/geopoppy:lizmap_rpi_3.2.1
    restart: always
    ports:
     - 80:80
     - 443:443
    volumes:
     - /home/pirate/geopoppy/qgis/geopoppy:/geopoppy
     - /home/pirate/geopoppy/var:/var/www/websig/lizmap/var     
  map:
    image: jancelin/geopoppy:qgis3server
    environment:
      PGSERVICEFILE: /srv/etc/pg_service.conf
      QGSRV_CACHE_ROOTDIR: /srv/projects
      QGSRV_CACHE_SIZE: '20'
      QGSRV_LOGGING_LEVEL: DEBUG
      QGSRV_USER: 1000:1000
      ROUTER_HOST: map
    volumes:
      - /home/pirate/geopoppy/qgis:/srv/projects
      - /home/pirate/geopoppy/etc:/srv/etc:ro
      - /home/pirate/geopoppy/wps-data:/srv/data
    restart: always
    expose:
      - 8080
    ports:
      - 8081:8080
  redis:
    image: redis:4
    volumes:
      - /home/pirate/geopoppy/redis:/data
    restart: always
  cloud:
    image: valentinalexeev/rpi-cloudcmd
    restart: always
    ports:
      - 8000:8000
    volumes:
      - /home/pirate/geopoppy:/mnt/fs  
  postgis:
    image: jancelin/geopoppy:postgres10-2.4-arm32_1
    restart: unless-stopped
    ports:
      - 5432:5432
    expose:
      - 5432
    entrypoint: >
      bash -c "cp  /home/setup-database.sh / &&
               /docker-entrypoint.sh"
    environment:
      - ALLOW_IP_RANGE=0.0.0.0/0
      - POSTGRES_USER=docker
      - POSTGRES_DBNAME=geopoppy
      - POSTGRES_DUMP=geopoppy.sql
    volumes:
      - /home/pirate/geopoppy/postgresql:/var/lib/postgresql
      - /home/pirate:/home
  tracking:
    image: jancelin/geopoppy:tracking_1_0
#    build:
#      context: https://github.com/jancelin/geo-poppy.git#dev:/tracking
    restart: "no"
    volumes:
      - /dev:/dev
    privileged: true
  portainer:
    image: portainer/portainer:linux-arm
    restart: always
    ports:
     - 9000:9000
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - /home/pirate/geopoppy/portainer:/data
