# Rename to docker-compose.yml
# play with HYPRIOT-OS-32bits : https://blog.hypriot.com/downloads/
# Flash microSD with etcher: https://etcher.io/
# MAINTAINER Julien Ancelin <julien.ancelin@inra.fr>
version: '3.2'
services:
  web:
    image: nginx:1
    volumes:
      - ${PWD}/geopoppy/etc/nginx.conf:/etc/nginx/nginx.conf
      - ${PWD}/geopoppy/var/log/nginx:/var/log/nginx
      - ${PWD}/geopoppy:/srv/lizmap
    ports:
      - 80:80
    restart: unless-stopped
  lizmap:
    image: jancelin/geopoppy:rpi_lizmap_client_3-2rc6_32
    command: 
      - php-fpm
    environment:
      LIZMAP_WPS_URL: http://wps:8080/ # According to your configuration
      LIZMAP_CACHESTORAGETYPE: redis   
      LIZMAP_CACHEREDISDB: '1'
      LIZMAP_USER: '1010'
      LIZMAP_WMSSERVERURL: http://map:8080/ows/
      LIZMAP_CACHEREDISHOST: redis
      LIZMAP_HOME: /srv/lizmap
    expose:
      - 9000
    volumes:
      - ${PWD}/geopoppy/qgis:/srv/projects
      - ${PWD}/geopoppy/var/lizmap-theme-config:/www/lizmap/var/lizmap-theme-config
      - ${PWD}/geopoppy/var/lizmap-config:/www/lizmap/var/config
      - ${PWD}/geopoppy/var/lizmap-db:/www/lizmap/var/db
      - ${PWD}/geopoppy/www:/www/lizmap/www
      - ${PWD}/geopoppy/var/log/lizmap:/www/lizmap/var/log
    restart: unless-stopped
  map:
    image: jancelin/geopoppy:qgis3server
    environment:
      PGSERVICEFILE: /srv/etc/pg_service.conf
      QGSRV_CACHE_ROOTDIR: /srv/projects
      QGSRV_CACHE_SIZE: '20'
      QGSRV_LOGGING_LEVEL: DEBUG
      QGSRV_USER: 1000:1000
      ROUTER_HOST: map
    volumes:
      - ${PWD}/geopoppy/qgis:/srv/projects
      - ${PWD}/geopoppy/etc:/srv/etc:ro
      - ${PWD}/geopoppy/wps-data:/srv/data
    restart: unless-stopped
    expose:
      - 8080
    ports:
      - 8081:8080
  redis:
    image: redis:4
    volumes:
      - ${PWD}/geopoppy/redis:/data
    restart: unless-stopped
  cloud:
    image: valentinalexeev/rpi-cloudcmd
    restart: always
    ports:
      - 8000:8000
    volumes:
      - ${PWD}/geopoppy:/mnt/fs  
  postgis:
    image: jancelin/geopoppy:postgres10-2.4-arm32_1
    restart: unless-stopped
    ports:
      - 5432:5432
    expose:
      - 5432
    entrypoint: >
      bash -c "cp  /home/setup-database.sh / &&
               /docker-entrypoint.sh"
    environment:
      - ALLOW_IP_RANGE=0.0.0.0/0
      - POSTGRES_USER=docker
      - POSTGRES_DBNAME=geopoppy
      - POSTGRES_DUMP=geopoppy.sql
    volumes:
      - ${PWD}/geopoppy/postgresql:/var/lib/postgresql
      - /home/pirate:/home
  tracking:
    image: jancelin/geopoppy:tracking_1_0
#    build:
#      context: https://github.com/jancelin/geo-poppy.git#dev:/tracking
    restart: "no"
    volumes:
      - /dev:/dev
    privileged: true
  portainer:
    image: portainer/portainer:linux-arm
    restart: always
    ports:
     - 9000:9000
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - ${PWD}/geopoppy/portainer:/data
