version: '3'
services:
      
  lizmap:
    image: jancelin/docker-lizmap:3.1.4
    restart: on-failure
    depends_on:
     - qgiserver
     - redis
    ports:
     - 80:80
     - 443:443
    volumes:
     - c:\Users\disa\dockerData\lizmap\project:/home:ro
     - c:\Users\disa\dockerData\lizmap\var:/var/www/websig/lizmap/var
    links:
     - qgiserver:qgiserver
     - redis:redis
     
  qgiserver:
    image: jancelin/qgis-server:2.14LTR-wfsOutputExtension
    restart: on-failure
    volumes:
      - c:\Users\disa\dockerData\lizmap\project:/home
    expose:
      - 80
      
  redis:
    image: redis:alpine
    restart: on-failure
    volumes:
      - c:\Users\disa\dockerData\lizmap\redis:/data
    expose:
      - 6379

  postgis:
    #image: kartoza/postgis:9.5-2.2
    image: jancelin/postgisgeo
    #build: 
      #context: c:\Users\disa\dockerData\postgres\install
      #dockerfile: Dockerfile 
    restart: on-failure
    ports:
      - 5432:5432
    expose:
      - 5432
    #volumes:
      #- c:\Users\disa\dockerData\postgres:/var/lib/postgresql
    environment:
      - ALLOW_IP_RANGE=0.0.0.0/0
      
  pgadmin4:
    image: chorss/docker-pgadmin4
    restart: on-failure
    ports:
      - 5050:5050
    volumes:
      - c:\Users\disa\dockerData\pgadmin4:/data
