version: '2'
services:
     
  postgiscollec:
    image: jancelin/geopoppy:postgiscollec-0.3
    restart: always
#    ports:
#     - "5433:5432"
    expose:
      - 5432
    volumes:
#          Pensez a installer le dossier des data avant !!!!
#          wget --no-check-certificate -P /home/pi https://github.com/jancelin/geo-poppy/blob/master/collec/db/postgres_data_collec_auto.tar
#          tar xvfz /home/pi/postgres_data_collec_auto.tar ---no-check-certificate -p --same-owner -C /
     - "/home/pi/collec/postgres_data_collec_auto:/var/lib/postgresql"
       
  collec:
    image: jancelin/geopoppy:collec-0.3
    restart: always
    ports:
      - 80:80
      - 443:443
    links:
      - postgiscollec:postgiscollec
      
# Collec est accessible à cette adresse: https://mon_ip/collec-master
# Login: admindemo
# Password: admin_007
